/**
 * 日报渲染器
 * 保存 Markdown 文件到对应目录
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_BASE = path.join(__dirname, '..');

/**
 * 保存日报到文件
 * @param {string} markdown - Markdown 内容
 * @param {string} lang - 语言 (zh|en)
 * @param {string} date - 日期 (YYYY-MM-DD)
 * @returns {string} 保存的文件路径
 */
export function saveReport(markdown, lang, date) {
    // 确定输出目录
    const dir = path.join(OUTPUT_BASE, lang, date.substring(0, 4));
    fs.mkdirSync(dir, { recursive: true });

    // 文件名
    const filename = lang === 'zh' ? `${date}.md` : `today.md`;
    const outputPath = path.join(dir, filename);

    // 写入文件
    fs.writeFileSync(outputPath, markdown, 'utf8');

    // 同时更新今日链接文件（英文版）
    if (lang === 'en') {
        const todayPath = path.join(OUTPUT_BASE, 'en/today.md');
        fs.writeFileSync(todayPath, markdown, 'utf8');
    }

    return outputPath;
}

/**
 * 生成 GitHub Pages 索引页
 */
export function generateIndex() {
    const indexPath = path.join(OUTPUT_BASE, 'index.html');
    const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI 日报</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #333; }
        .lang-switch { margin: 20px 0; }
        .lang-switch a { margin-right: 20px; }
    </style>
</head>
<body>
    <h1>🤖 AI 日报</h1>
    <div class="lang-switch">
        <a href="./zh/">📥 中文日报</a>
        <a href="./en/">🇬🇧 English Daily</a>
    </div>
    <p>每日自动生成的 AI 行业日报，涵盖技术趋势、产品动态、市场竞争分析。</p>
    <hr>
    <p><small>Generated by AI Daily Report System</small></p>
</body>
</html>`;
    
    fs.writeFileSync(indexPath, html, 'utf8');
    console.log('✓ 已生成 index.html');
}

/**
 * 生成中文日报列表页
 */
export function generateZhIndex() {
    const zhDir = path.join(OUTPUT_BASE, 'zh');
    const years = fs.readdirSync(zhDir).filter(f => /^\d{4}$/.test(f));
    
    let html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>AI 日报 - 中文</title>
</head>
<body>
    <h1>📥 AI 日报（中文）</h1>
    <ul>`;
    
    for (const year of years.sort().reverse()) {
        const yearDir = path.join(zhDir, year);
        const files = fs.readdirSync(yearDir)
            .filter(f => f.endsWith('.md'))
            .sort()
            .reverse();
        
        for (const file of files) {
            const date = file.replace('.md', '');
            html += `    <li><a href="./${year}/${file}">${date}</a></li>\n`;
        }
    }
    
    html += `    </ul>
</body>
</html>`;
    
    fs.writeFileSync(path.join(zhDir, 'index.html'), html, 'utf8');
}
