/**
 * 日报渲染器
 */

const fs = require('fs');
const path = require('path');

const OUTPUT_BASE = path.join(__dirname, '..');

function saveReport(markdown, lang, date) {
    const dir = path.join(OUTPUT_BASE, lang, date.substring(0, 4));
    fs.mkdirSync(dir, { recursive: true });

    const filename = lang === 'zh' ? `${date}.md` : `today.md`;
    const outputPath = path.join(dir, filename);
    fs.writeFileSync(outputPath, markdown, 'utf8');

    // Also create latest link for English
    if (lang === 'en') {
        const todayPath = path.join(OUTPUT_BASE, 'en', 'today.md');
        fs.writeFileSync(todayPath, markdown, 'utf8');
    }

    return outputPath;
}

function generateIndex() {
    const indexPath = path.join(OUTPUT_BASE, 'index.html');
    const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI 日报</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #333; }
        .lang-switch { margin: 20px 0; }
        .lang-switch a { margin-right: 20px; color: #0366d6; text-decoration: none; }
        .lang-switch a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>🤖 AI 日报</h1>
    <div class="lang-switch">
        <a href="./zh/">📥 中文日报</a>
        <a href="./en/">🇬🇧 English Daily</a>
    </div>
    <p>每日自动生成的 AI 行业日报，涵盖技术趋势、产品动态、市场竞争分析。</p>
    <hr>
    <p><small>Generated by AI Daily Report System | Powered by GitHub Actions</small></p>
</body>
</html>`;
    
    fs.writeFileSync(indexPath, html, 'utf8');
    console.log('✓ 已生成 index.html');
}

function generateZhIndex() {
    const zhDir = path.join(OUTPUT_BASE, 'zh');
    if (!fs.existsSync(zhDir)) {
        fs.mkdirSync(zhDir, { recursive: true });
    }
    
    const years = fs.readdirSync(zhDir).filter(f => /^\d{4}$/.test(f));
    
    let html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>AI 日报 - 中文</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        a { color: #0366d6; text-decoration: none; }
        a:hover { text-decoration: underline; }
        li { margin: 8px 0; }
    </style>
</head>
<body>
    <h1>📥 AI 日报（中文）</h1>
    <p><a href="../">← 返回首页</a></p>
    <ul>`;
    
    for (const year of years.sort().reverse()) {
        const yearDir = path.join(zhDir, year);
        const files = fs.readdirSync(yearDir)
            .filter(f => f.endsWith('.md'))
            .sort().reverse();
        
        for (const file of files) {
            const date = file.replace('.md', '');
            html += `    <li><a href="./${year}/${file}">${date}</a></li>\n`;
        }
    }
    
    html += `    </ul>
</body>
</html>`;
    
    fs.writeFileSync(path.join(zhDir, 'index.html'), html, 'utf8');
}

module.exports = { saveReport, generateIndex, generateZhIndex };
